# Generated by Django 4.2.7 on 2024-02-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_baseorder_customer_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketLeaguePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rocketLeague/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeagueRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rocketLeague/images/')),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeagueSeasonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rocketLeague/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeagueTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rocketLeague/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeagueTournamentOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rocketLeague_ournament_order', serialize=False, to='accounts.baseorder')),
                ('current_league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_league', to='rocketLeague.rocketleaguetournament')),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeagueSeasonalOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rocketLeague_seasonal_order', serialize=False, to='accounts.baseorder')),
                ('number_of_wins', models.IntegerField(default=5)),
                ('current_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='rocketLeague.rocketleagueseasonal')),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeagueRankedOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rocketLeague_division_order', serialize=False, to='accounts.baseorder')),
                ('ranked_type', models.IntegerField(blank=True, choices=[(1, '1 vs 1 Ranked'), (2, '2 vs 2 Ranked'), (3, '3 vs 3 Ranked')], null=True)),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='rocketLeague.rocketleaguerank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='rocketLeague.rocketleaguerank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='rocketLeague.rocketleaguerank')),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeaguePlacementOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rocketLeague_placement_order', serialize=False, to='accounts.baseorder')),
                ('number_of_match', models.IntegerField(default=10)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last_rank', to='rocketLeague.rocketleagueplacement')),
            ],
        ),
        migrations.CreateModel(
            name='RocketLeagueDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_I_to_II', models.FloatField(default=0)),
                ('from_II_to_III', models.FloatField(default=0)),
                ('from_III_to_I_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='rocketLeague.rocketleaguerank')),
            ],
        ),
    ]
