# Generated by Django 4.2.7 on 2024-03-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_baseorder_game_id_remove_baseorder_game_name_and_more'),
        ('rocketLeague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketLeagueDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rocketLeague_division_order', serialize=False, to='accounts.baseorder')),
                ('ranked_type', models.IntegerField(blank=True, choices=[(1, '1 vs 1 Ranked'), (2, '2 vs 2 Ranked'), (3, '3 vs 3 Ranked')], null=True)),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('current_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('reached_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='rocketLeague.rocketleaguerank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='rocketLeague.rocketleaguerank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='rocketLeague.rocketleaguerank')),
            ],
        ),
        migrations.DeleteModel(
            name='RocketLeagueRankedOrder',
        ),
    ]
