# Generated by Django 4.2.7 on 2024-03-17 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rocketLeague', '0003_rocketleagueseasonalorder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketleagueplacementorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
