# Generated by Django 4.2.7 on 2024-04-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocketLeague', '0005_rocketleagueplacement1_rocketleaguerank1_and_more'),
        ('booster', '0036_alter_booster_achived_rank_rl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RocketLeagueRank',
        ),
        migrations.DeleteModel(
            name='RocketLeagueSeasonal',
        ),
        migrations.DeleteModel(
            name='RocketLeagueTournament',
        ),
    ]
