# Generated by Django 4.2.7 on 2024-04-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0037_alter_booster_achived_rank_rl'),
        ('rocketLeague', '0007_rocketleagueplacement_rocketleaguerank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RocketLeagueRank1',
        ),
        migrations.DeleteModel(
            name='RocketLeagueSeasonal1',
        ),
        migrations.DeleteModel(
            name='RocketLeagueTournament1',
        ),
    ]
