# Generated by Django 5.0.4 on 2024-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocketLeague', '0008_delete_rocketleaguerank1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketleaguedivisionorder',
            name='ranked_type',
            field=models.IntegerField(choices=[(1, '1 vs 1 Ranked'), (2, '2 vs 2 Ranked'), (3, '3 vs 3 Ranked')], default=1),
            preserve_default=False,
        ),
    ]
