# Generated by Django 4.2.7 on 2024-01-06 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildRiftPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wildRift/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WildRiftRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='wildRift/images/')),
            ],
        ),
        migrations.CreateModel(
            name='WildRiftTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_IV_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_IV_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='wildRift.wildriftrank')),
            ],
        ),
        migrations.CreateModel(
            name='WildRiftPlacementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_match', models.IntegerField(default=5)),
                ('price', models.FloatField(default=0)),
                ('invoice', models.FloatField(default=0)),
                ('booster_percent1', models.IntegerField(default=50)),
                ('booster_percent2', models.IntegerField(default=60)),
                ('booster_percent3', models.IntegerField(default=70)),
                ('booster_percent4', models.IntegerField(default=80)),
                ('duo_boosting', models.BooleanField(blank=True, default=False)),
                ('select_booster', models.BooleanField(blank=True, default=False)),
                ('turbo_boost', models.BooleanField(blank=True, default=False)),
                ('streaming', models.BooleanField(blank=True, default=False)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booster', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booster_placement', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_placement', to=settings.AUTH_USER_MODEL)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last_rank', to='wildRift.wildriftplacement')),
            ],
        ),
        migrations.CreateModel(
            name='WildRiftMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_number', models.IntegerField(choices=[(2, '2 Marks'), (3, '3 Marks'), (4, '4 Marks'), (5, '5 Marks'), (6, '6 Marks')])),
                ('mark_1', models.FloatField(default=0)),
                ('mark_2', models.FloatField(default=0)),
                ('mark_3', models.FloatField(default=0)),
                ('mark_4', models.FloatField(default=0)),
                ('mark_5', models.FloatField(default=0)),
                ('mark_6', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='wildRift.wildriftrank')),
                ('tier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier_mark', to='wildRift.wildrifttier')),
            ],
        ),
        migrations.CreateModel(
            name='WildRiftDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wildrift_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('current_marks', models.IntegerField(blank=True, choices=[(0, '0 Marks'), (1, '1 Marks'), (2, '2 Marks'), (3, '3 Marks'), (4, '4 Marks'), (5, '5 Marks'), (6, '6 Marks')], null=True)),
                ('reached_marks', models.IntegerField(blank=True, choices=[(0, '0 Marks'), (1, '1 Marks'), (2, '2 Marks'), (3, '3 Marks'), (4, '4 Marks'), (5, '5 Marks'), (6, '6 Marks')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='wildRift.wildriftrank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='wildRift.wildriftrank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='wildRift.wildriftrank')),
            ],
        ),
    ]
