# Generated by Django 4.2.7 on 2024-02-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0002_delete_wildriftplacementorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WildRiftPlacement',
        ),
    ]
