# Generated by Django 4.2.7 on 2024-02-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0003_delete_wildriftplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildriftdivisionorder',
            name='booster_champions',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
