# Generated by Django 4.2.7 on 2024-03-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0004_wildriftdivisionorder_booster_champions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildriftdivisionorder',
            old_name='booster_champions',
            new_name='select_champion',
        ),
    ]
