# Generated by Django 4.2.7 on 2024-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_champion_delete_championc'),
        ('wildRift', '0005_rename_booster_champions_wildriftdivisionorder_select_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildriftdivisionorder',
            name='champions',
            field=models.ManyToManyField(blank=True, related_name='wr_division_champions', to='customer.champion'),
        ),
    ]
