# Generated by Django 4.2.7 on 2024-04-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0007_wildriftrank1_and_more'),
        ('booster', '0025_alter_booster_achived_rank_wr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WildRiftRank',
        ),
    ]
