# Generated by Django 4.2.7 on 2024-04-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0012_delete_wildriftrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildRiftRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='wildRift/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='wildriftdivisionorder',
            name='current_rank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='wildRift.wildriftrank'),
        ),
        migrations.AlterField(
            model_name='wildriftdivisionorder',
            name='desired_rank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='wildRift.wildriftrank'),
        ),
        migrations.AlterField(
            model_name='wildriftdivisionorder',
            name='reached_rank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='wildRift.wildriftrank'),
        ),
        migrations.AlterField(
            model_name='wildriftmark',
            name='rank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='wildRift.wildriftrank'),
        ),
        migrations.AlterField(
            model_name='wildrifttier',
            name='rank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='wildRift.wildriftrank'),
        ),
    ]
