# Generated by Django 4.2.7 on 2024-04-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0028_alter_booster_achived_rank_wr'),
        ('wildRift', '0013_wildriftrank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WildRiftRank1',
        ),
    ]
