# Generated by Django 4.2.7 on 2024-04-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0031_alter_booster_achived_rank_wr'),
        ('wildRift', '0019_wildriftrank1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WildRiftRank',
        ),
    ]
