# Generated by Django 4.2.7 on 2024-04-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0023_wildriftrank1_and_more'),
        ('booster', '0033_alter_booster_achived_rank_wr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WildRiftRank',
        ),
    ]
