# Generated by Django 4.2.7 on 2024-04-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0035_alter_booster_achived_rank_wr'),
        ('wildRift', '0028_delete_wildriftrank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WildRiftRank1',
            new_name='WildRiftRank',
        ),
    ]
