# Generated by Django 4.2.7 on 2024-04-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0029_rename_wildriftrank1_wildriftrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildriftmark',
            name='tier',
        ),
    ]
