# Generated by Django 5.0.4 on 2024-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='order_image2',
            field=models.ImageField(default='', upload_to='blog/'),
            preserve_default=False,
        ),
    ]
