# Generated by Django 4.2.7 on 2024-03-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Champions',
            new_name='Champion',
        ),
    ]
