# Generated by Django 4.2.7 on 2024-03-22 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('customer', '0002_rename_champions_champion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='None/champions')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champions', to='games.game')),
            ],
            options={
                'unique_together': {('name', 'game')},
            },
        ),
        migrations.DeleteModel(
            name='Champion',
        ),
    ]
