# Generated by Django 4.2.7 on 2024-02-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_baseorder_customer_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoW_25_RPs_Price_2x2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WoW_25_RPs_Price_3x3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='WoWRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='wow/images/')),
                ('start_RP', models.IntegerField()),
                ('end_RP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WoWArenaBoostOrder',
            fields=[
                ('is_Arena_2x2', models.BooleanField(default=True)),
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(default=0)),
                ('reached_division', models.IntegerField(default=0)),
                ('desired_division', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choose_agents', models.BooleanField(blank=True, default=True, null=True)),
                ('current_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_current_rank', to='WorldOfWarcraft.wowrank')),
                ('desired_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_desired_rank', to='WorldOfWarcraft.wowrank')),
                ('reached_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_reached_rank', to='WorldOfWarcraft.wowrank')),
            ],
        ),
    ]
