# Generated by Django 4.0 on 2024-03-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0011_alter_booster_achived_rank_wow'),
        ('WorldOfWarcraft', '0002_worldofwarcraftarenaboostorder_worldofwarcraftrank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WoWRank',
        ),
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='current_rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_current_rank', to='WorldOfWarcraft.worldofwarcraftrank'),
        ),
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='desired_rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_desired_rank', to='WorldOfWarcraft.worldofwarcraftrank'),
        ),
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='reached_rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_reached_rank', to='WorldOfWarcraft.worldofwarcraftrank'),
        ),
    ]
