# Generated by Django 4.0 on 2024-03-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0003_delete_wowrank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldofwarcraftarenaboostorder',
            name='choose_champions',
        ),
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='current_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='reached_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftrpsprice',
            name='price_of_2vs2',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftrpsprice',
            name='price_of_3vs3',
            field=models.FloatField(default=2),
        ),
    ]
