# Generated by Django 5.0.10 on 2025-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0004_add_boost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='boost_method',
            field=models.CharField(max_length=50),
        ),
    ]
