# Generated by Django 4.2.7 on 2024-03-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0004_remove_worldofwarcraftarenaboostorder_choose_champions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldofwarcraftarenaboostorder',
            old_name='is_Arena_2x2',
            new_name='is_arena_2vs2',
        ),
    ]
