# Generated by Django 4.2.7 on 2024-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0005_rename_is_arena_2x2_worldofwarcraftarenaboostorder_is_arena_2vs2'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftrank',
            name='end_RP',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftrank',
            name='start_RP',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
