# Generated by Django 4.2.7 on 2024-04-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0009_worldofwarcraftrank_and_more'),
        ('booster', '0021_alter_booster_achived_rank_wow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldOfWarcraftRank1',
        ),
    ]
