# Generated by Django 4.2.7 on 2024-04-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0010_delete_worldofwarcraftrank1'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldOfWarcraftRank1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='wow/images/')),
                ('start_RP', models.PositiveIntegerField(null=True)),
                ('end_RP', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='current_rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_current_rank', to='WorldOfWarcraft.worldofwarcraftrank1'),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='desired_rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_desired_rank', to='WorldOfWarcraft.worldofwarcraftrank1'),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='reached_rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wow_reached_rank', to='WorldOfWarcraft.worldofwarcraftrank1'),
        ),
    ]
