# Generated by Django 4.2.7 on 2024-04-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0011_worldofwarcraftrank1_and_more'),
        ('booster', '0022_alter_booster_achived_rank_wow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldOfWarcraftRank',
        ),
    ]
