# Generated by Django 4.2.7 on 2024-04-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0014_delete_worldofwarcraftrank1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldofwarcraftrank',
            name='end_RP',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftrank',
            name='start_RP',
        ),
    ]
