# Generated by Django 5.0.4 on 2024-07-15 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0017_worldofwarcraftraidsimpleorder'),
        ('accounts', '0060_alter_baseorder_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldOfWarcraftRaidBundleOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_raid_bundle_order', serialize=False, to='accounts.baseorder')),
                ('difficulty', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wow_raid_bundle_order_bundles', to='WorldOfWarcraft.worldofwarcraftbundle')),
            ],
        ),
    ]
