# Generated by Django 5.0.4 on 2024-08-02 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0018_worldofwarcraftraidbundleorder'),
        ('accounts', '0060_alter_baseorder_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeystonePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldOfWarcraftDungeonSimpleOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_dungeon_simple_order', serialize=False, to='accounts.baseorder')),
                ('keystone', models.IntegerField()),
                ('keys', models.IntegerField()),
                ('traders', models.CharField(max_length=300)),
                ('traders_armor_type', models.CharField(max_length=300)),
                ('map_preferred', models.CharField(max_length=300)),
                ('algathar_academy', models.IntegerField()),
                ('azure_vault', models.IntegerField()),
                ('brackenhide_hollow', models.IntegerField()),
                ('halls_of_infusion', models.IntegerField()),
                ('neltharus', models.IntegerField()),
                ('nokhud_offensive', models.IntegerField()),
                ('ruby_life_pools', models.IntegerField()),
                ('uldaman_legacy_of_tyr', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
