# Generated by Django 5.0.4 on 2024-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0019_keystoneprice_worldofwarcraftdungeonsimpleorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='algathar_academy',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='azure_vault',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='brackenhide_hollow',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='halls_of_infusion',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='neltharus',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='nokhud_offensive',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='ruby_life_pools',
        ),
        migrations.RemoveField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='uldaman_legacy_of_tyr',
        ),
        migrations.AddField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='maps',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
