# Generated by Django 5.0.4 on 2024-09-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0020_remove_worldofwarcraftdungeonsimpleorder_algathar_academy_and_more'),
        ('accounts', '0060_alter_baseorder_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowLevelUpOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wow_level_up_order', serialize=False, to='accounts.baseorder')),
                ('current_level', models.IntegerField(blank=True, default=1)),
                ('reached_level', models.IntegerField(blank=True, default=1, null=True)),
                ('desired_level', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WowLevelUpPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=10)),
            ],
        ),
    ]
