# Generated by Django 5.0.4 on 2024-09-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0021_wowleveluporder_wowlevelupprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='boost_method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='rank1_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worldofwarcraftarenaboostorder',
            name='tournament_player',
            field=models.BooleanField(default=False),
        ),
    ]
