# Generated by Django 5.0.4 on 2024-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0022_worldofwarcraftarenaboostorder_boost_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofwarcraftraidsimpleorder',
            name='boost_method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldofwarcraftraidsimpleorder',
            name='loot_priority',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
