# Generated by Django 5.0.4 on 2024-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0023_worldofwarcraftraidsimpleorder_boost_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldofwarcraftraidbundleorder',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='worldofwarcraftraidbundleorder',
            name='boost_method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldofwarcraftraidbundleorder',
            name='loot_priority',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
