# Generated by Django 5.0.4 on 2024-09-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0024_remove_worldofwarcraftraidbundleorder_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='boost_method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='timed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
