# Generated by Django 5.0.4 on 2024-09-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0025_worldofwarcraftdungeonsimpleorder_boost_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='map_preferred',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='maps',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='traders',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='traders_armor_type',
            field=models.CharField(max_length=2000),
        ),
    ]
