# Generated by Django 5.0.4 on 2024-09-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0026_alter_worldofwarcraftdungeonsimpleorder_map_preferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='boost_method',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='map_preferred',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='maps',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='traders',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='worldofwarcraftdungeonsimpleorder',
            name='traders_armor_type',
            field=models.CharField(max_length=300),
        ),
    ]
