# Generated by Django 5.0.4 on 2024-10-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0027_alter_worldofwarcraftdungeonsimpleorder_boost_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldofwarcraftarenaboostorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
