# Generated by Django 4.2.7 on 2024-02-25 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_promocode_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overwatch2Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='overwatch2/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Overwatch2Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_IV_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_IV_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='overwatch2.overwatch2rank')),
            ],
        ),
        migrations.CreateModel(
            name='Overwatch2Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_number', models.IntegerField(choices=[(2, '2 Marks'), (3, '3 Marks'), (4, '4 Marks'), (5, '5 Marks'), (6, '6 Marks')])),
                ('mark_1', models.FloatField(default=0)),
                ('mark_2', models.FloatField(default=0)),
                ('mark_3', models.FloatField(default=0)),
                ('mark_4', models.FloatField(default=0)),
                ('mark_5', models.FloatField(default=0)),
                ('mark_6', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='overwatch2.overwatch2rank')),
                ('tier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier_mark', to='overwatch2.overwatch2tier')),
            ],
        ),
        migrations.CreateModel(
            name='Overwatch2DivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='overwatch2_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('current_marks', models.IntegerField(blank=True, choices=[(0, '0 Marks'), (1, '1 Marks'), (2, '2 Marks'), (3, '3 Marks'), (4, '4 Marks'), (5, '5 Marks'), (6, '6 Marks')], null=True)),
                ('reached_marks', models.IntegerField(blank=True, choices=[(0, '0 Marks'), (1, '1 Marks'), (2, '2 Marks'), (3, '3 Marks'), (4, '4 Marks'), (5, '5 Marks'), (6, '6 Marks')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='overwatch2.overwatch2rank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='overwatch2.overwatch2rank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='overwatch2.overwatch2rank')),
            ],
        ),
    ]
