# Generated by Django 4.2.7 on 2024-03-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overwatch2divisionorder',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'DPS'), (2, 'TANK'), (3, 'SUPPORT')], default=0),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')]),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '0-19 %'), (2, '20-39 %'), (3, '40-59 %'), (4, '60-79 %'), (5, '80-99 %')]),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='current_rank',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='current_rank', to='overwatch2.overwatch2rank'),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')]),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='desired_rank',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='desired_rank', to='overwatch2.overwatch2rank'),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '0-19 %'), (2, '20-39 %'), (3, '40-59 %'), (4, '60-79 %'), (5, '80-99 %')], null=True),
        ),
        migrations.AlterField(
            model_name='overwatch2divisionorder',
            name='reached_rank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reached_rank', to='overwatch2.overwatch2rank'),
        ),
    ]
