# Generated by Django 4.2.7 on 2024-03-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_baseorder_game_id_remove_baseorder_game_name_and_more'),
        ('overwatch2', '0002_overwatch2divisionorder_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overwatch2Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='overwatch2/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='overwatch2tier',
            old_name='from_I_to_IV_next',
            new_name='from_I_to_V_next',
        ),
        migrations.RemoveField(
            model_name='overwatch2mark',
            name='mark_6',
        ),
        migrations.RemoveField(
            model_name='overwatch2mark',
            name='tier',
        ),
        migrations.AddField(
            model_name='overwatch2tier',
            name='from_V_to_IV',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='overwatch2mark',
            name='mark_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Overwatch2PlacementOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ovw2_placement_order', serialize=False, to='accounts.baseorder')),
                ('number_of_match', models.IntegerField(default=5)),
                ('choose_champions', models.BooleanField(blank=True, default=False, null=True)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ovw2_last_rank', to='overwatch2.overwatch2placement')),
            ],
        ),
    ]
