# Generated by Django 4.2.7 on 2024-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch2', '0003_overwatch2placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overwatch2mark',
            name='mark_number',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
