# Generated by Django 4.2.7 on 2024-03-17 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch2', '0004_alter_overwatch2mark_mark_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overwatch2placementorder',
            old_name='choose_champions',
            new_name='select_champions',
        ),
        migrations.AddField(
            model_name='overwatch2divisionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='overwatch2placementorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overwatch2placementorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
