# Generated by Django 4.2.7 on 2024-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch2', '0005_rename_choose_champions_overwatch2placementorder_select_champions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overwatch2placementorder',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'DPS'), (2, 'TANK'), (3, 'SUPPORT')], default=0),
        ),
    ]
