# Generated by Django 4.2.7 on 2024-03-17 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tftdivisionorder',
            name='speed_up_boost',
        ),
        migrations.RemoveField(
            model_name='tftplacementorder',
            name='speed_up_boost',
        ),
        migrations.AddField(
            model_name='tftplacementorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
