# Generated by Django 4.0 on 2024-03-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0028_alter_room_unique_together_remove_room_booster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('is_for_admins', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('booster', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booster_room', to='accounts.baseuser')),
                ('customer', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': False}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_room', to='accounts.baseuser')),
            ],
            options={
                'unique_together': {('name', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('msg_type', models.IntegerField(choices=[(1, 'normal'), (2, 'tip')], default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.baseuser')),
            ],
        ),
    ]
