# Generated by Django 4.2.7 on 2024-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'tip'), (3, 'changes'), (4, 'admin')], default=1),
        ),
    ]
