# Generated by Django 4.2.7 on 2023-12-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booster',
        ),
        migrations.RemoveField(
            model_name='room',
            name='customer',
        ),
    ]
