# Generated by Django 4.2.7 on 2023-12-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booster',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booster_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
