# Generated by Django 4.2.7 on 2023-12-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_created_on_alter_room_name_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
