# Generated by Django 4.2.7 on 2023-12-10 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_room_booster_room_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
