# Generated by Django 4.2.7 on 2024-02-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_promocode_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dota2_50_MMR_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dota2Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='dota2/images/')),
                ('start_RP', models.IntegerField()),
                ('end_RP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dota2RankBoostOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dota2_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(default=0)),
                ('reached_division', models.IntegerField(default=0)),
                ('desired_division', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choose_agents', models.BooleanField(blank=True, default=True, null=True)),
                ('role', models.CharField(blank=True, choices=[(1, 'Core'), (2, 'Support')], default=1, max_length=100, null=True)),
                ('current_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dota2_current_rank', to='dota2.dota2rank')),
                ('desired_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dota2_desired_rank', to='dota2.dota2rank')),
                ('reached_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dota2_reached_rank', to='dota2.dota2rank')),
            ],
        ),
    ]
