# Generated by Django 4.2.7 on 2024-02-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Core'), (2, 'Support')], null=True),
        ),
    ]
