# Generated by Django 4.2.7 on 2024-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0002_alter_dota2rankboostorder_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dota2rankboostorder',
            old_name='choose_agents',
            new_name='select_champion',
        ),
        migrations.AddField(
            model_name='dota2rankboostorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dota2rankboostorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
