# Generated by Django 4.2.7 on 2024-03-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0003_rename_choose_agents_dota2rankboostorder_select_champion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Core'), (2, 'Support')], null=True),
        ),
    ]
