# Generated by Django 4.2.7 on 2024-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0004_alter_dota2rankboostorder_current_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='current_division',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='desired_division',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dota2rankboostorder',
            name='reached_division',
            field=models.IntegerField(default=0),
        ),
    ]
