# Generated by Django 4.2.7 on 2024-03-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_tokenforpay_invoice'),
        ('dota2', '0005_alter_dota2rankboostorder_current_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dota2MmrPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_0_2000', models.FloatField(default=1)),
                ('price_2000_3000', models.FloatField(default=1)),
                ('price_3000_4000', models.FloatField(default=1)),
                ('price_4000_5000', models.FloatField(default=1)),
                ('price_5000_5500', models.FloatField(default=1)),
                ('price_5500_6000', models.FloatField(default=1)),
                ('price_6000_extra', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dota2Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='dota2/images/')),
                ('start_RP', models.IntegerField()),
                ('end_RP', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dota2PlacementOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dota2_placement_order', serialize=False, to='accounts.baseorder')),
                ('last_division', models.IntegerField(default=0)),
                ('number_of_match', models.IntegerField(default=0)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Core'), (2, 'Support')], null=True)),
                ('select_champion', models.BooleanField(blank=True, default=False, null=True)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last_rank', to='dota2.dota2placement')),
            ],
        ),
        migrations.DeleteModel(
            name='Dota2_50_MMR_Price',
        ),
    ]
