# Generated by Django 4.2.7 on 2024-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0006_dota2mmrprice_dota2placement_dota2placementorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dota2rankboostorder',
            name='mmr_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
