# Generated by Django 5.0.4 on 2024-10-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0007_dota2rankboostorder_mmr_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dota2rankboostorder',
            name='mmr_price',
        ),
        migrations.RemoveField(
            model_name='dota2rankboostorder',
            name='select_champion',
        ),
    ]
