# Generated by Django 4.2.7 on 2023-11-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
