# Generated by Django 4.2.7 on 2024-01-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='details',
            field=models.CharField(default='no details', max_length=300),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='game_name',
            field=models.CharField(default='game name', max_length=30),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='game_type',
            field=models.CharField(choices=[('D', 'Division'), ('P', 'Placement')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
