# Generated by Django 4.2.7 on 2024-01-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseorder_details_alter_baseorder_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='customer_server',
            field=models.IntegerField(blank=True, choices=[(1, 'Europa'), (2, 'America'), (3, 'Asia'), (4, 'Africa'), (5, 'Australia'), (6, 'North America'), (7, 'South America'), (8, 'Middle East'), (9, 'KRJP')], null=True),
        ),
    ]
