# Generated by Django 4.2.7 on 2023-11-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/accounts/'),
        ),
    ]
