# Generated by Django 5.0.10 on 2025-11-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_baseorder_real_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='progress_at_payment',
            field=models.FloatField(blank=True, help_text='Progress percentage at the time of payment', null=True),
        ),
    ]
