# Generated by Django 4.2.7 on 2024-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
