# Generated by Django 4.2.7 on 2024-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_promocode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_amount',
            field=models.FloatField(),
        ),
    ]
