# Generated by Django 4.2.7 on 2024-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_promocode_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
