# Generated by Django 4.2.7 on 2024-02-26 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0010_alter_promocode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseorder',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='booster',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booster_division', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='booster',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booster_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='accounts.baseorder'),
        ),
    ]
