# Generated by Django 4.2.7 on 2024-02-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0011_baseorder_content_type_baseorder_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
    ]
