# Generated by Django 4.2.7 on 2024-02-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_baseorder_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
