# Generated by Django 4.2.7 on 2024-02-26 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_baseorder_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
