# Generated by Django 4.2.7 on 2024-02-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_transaction_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='n', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tip_data',
            name='payer_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
