# Generated by Django 4.2.7 on 2024-02-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_room_name_alter_tip_data_payer_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'customer')},
        ),
    ]
