# Generated by Django 4.2.7 on 2024-02-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='promo_code',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
