# Generated by Django 4.2.7 on 2024-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_baseorder_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='promo_code',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
