# Generated by Django 4.2.7 on 2024-03-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '__first__'),
        ('accounts', '0022_alter_baseorder_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseorder',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='baseorder',
            name='game_name',
        ),
        migrations.AddField(
            model_name='baseorder',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game', to='games.game'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='accounts/images/'),
        ),
    ]
