# Generated by Django 4.0 on 2024-03-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_baseorder_payer_id_alter_baseuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
