# Generated by Django 4.0 on 2024-03-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_baseuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
