# Generated by Django 4.0 on 2024-03-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_baseuser_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='last_online',
            field=models.DateTimeField(null=True),
        ),
    ]
