# Generated by Django 4.0 on 2024-03-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_baseuser_last_online'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='booster',
        ),
        migrations.RemoveField(
            model_name='room',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
