# Generated by Django 4.2.7 on 2024-03-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_baseuser_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='activation_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='activation_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='rest_password_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='rest_password_time',
            field=models.DateTimeField(null=True),
        ),
    ]
