# Generated by Django 4.2.7 on 2024-03-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_baseuser_activation_code_baseuser_activation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.promocode'),
        ),
    ]
