# Generated by Django 4.2.7 on 2024-03-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_baseorder_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseorder',
            name='promo_code',
        ),
    ]
