# Generated by Django 4.2.7 on 2024-03-11 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_baseorder_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenforpay',
            name='invoice',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenforpay',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenforpay',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_order', to='accounts.baseorder'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tip', to='accounts.tip_data'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
