# Generated by Django 4.2.7 on 2024-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_tokenforpay_invoice_alter_tokenforpay_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenforpay',
            name='invoice',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
