# Generated by Django 4.2.7 on 2024-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_tokenforpay_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='game_type',
            field=models.CharField(choices=[('D', 'Division'), ('P', 'Placement'), ('A', 'Arena'), ('F', 'Faceit')], max_length=10, null=True),
        ),
    ]
