# Generated by Django 4.2.7 on 2024-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_baseorder_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='customer_username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='baseorder',
            name='pause',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
