# Generated by Django 4.2.7 on 2024-04-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_baseorder_customer_username_baseorder_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='finish_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/images/'),
        ),
    ]
