# Generated by Django 4.2.7 on 2024-04-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_baseorder_finish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosterpercent',
            name='booster_percent5',
            field=models.IntegerField(default=35),
        ),
    ]
