# Generated by Django 4.2.7 on 2024-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_boosterpercent_booster_percent5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='activation_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='activation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images/'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='rest_password_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='rest_password_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
