# Generated by Django 4.2.7 on 2024-04-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_baseuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='booster',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booster_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
