# Generated by Django 4.2.7 on 2024-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_baseorder_booster'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
