# Generated by Django 4.2.7 on 2024-04-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='profile_image',
        ),
    ]
