# Generated by Django 5.0.4 on 2024-04-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_delete_test_remove_baseuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='customer_gamename',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='customer_password',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='customer_username',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
