# Generated by Django 5.0.4 on 2024-04-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_baseorder_customer_gamename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
