# Generated by Django 5.0.4 on 2024-05-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_historicalbaseuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBaseUser',
        ),
    ]
