# Generated by Django 5.0.4 on 2024-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_delete_historicalbaseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='wins_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
