# Generated by Django 5.0.4 on 2024-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_baseorder_wins_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='customer_gamename',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='customer_username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
