# Generated by Django 5.0.4 on 2024-05-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_baseorder_customer_gamename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('value', models.CharField()),
            ],
        ),
    ]
