# Generated by Django 5.0.4 on 2024-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_captchaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('value', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='CaptchaImage',
        ),
    ]
