# Generated by Django 5.0.4 on 2024-05-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_captcha_delete_captchaimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='captcha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='accounts.captcha'),
        ),
    ]
