# Generated by Django 5.0.4 on 2024-06-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_transaction_amount_alter_transaction_notice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='payer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tip_data',
            name='invoice',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tip_data',
            name='payer_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenforpay',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
