# Generated by Django 5.0.4 on 2024-07-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_baseorder_payer_id_alter_promocode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='game_type',
            field=models.CharField(choices=[('D', 'Division'), ('P', 'Placement'), ('A', 'Arena'), ('F', 'Faceit'), ('R', 'Raid'), ('RB', 'Raid Bundle'), ('DU', 'Dungeon'), ('DB', 'Dungeon Bundle')], max_length=10, null=True),
        ),
    ]
