# Generated by Django 5.0.4 on 2024-09-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_baseorder_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenforpay',
            name='invoice',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
    ]
