# Generated by Django 5.0.4 on 2024-09-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_tokenforpay_game_info_alter_tokenforpay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenforpay',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
