# Generated by Django 5.0.4 on 2024-09-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_tokenforpay2_delete_tokenforpay'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenForPay2',
            new_name='TokenForPay',
        ),
    ]
