# Generated by Django 5.0.4 on 2024-10-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_tokenforpay_game_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='times_used',
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_percent',
            field=models.BooleanField(default=False),
        ),
    ]
