# Generated by Django 5.0.4 on 2024-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_remove_promocode_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='real_order_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
