# Generated by Django 5.0.10 on 2025-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_managercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField(db_index=True, max_length=64)),
                ('service_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['game_key', 'service_id'], name='admin_dashb_game_ke_7c0922_idx')],
                'unique_together': {('game_key', 'service_id')},
            },
        ),
    ]
