# Generated by Django 5.0.10 on 2025-09-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_pricingentry'),
    ]

    operations = [
    ]
