# Generated by Django 4.2.7 on 2024-02-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_baseorder_customer_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorOfKingsRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='hok/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HonorOfKingsTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_V_to_IV', models.FloatField(default=0)),
                ('from_IV_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_IV_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='honorOfKings.honorofkingsrank')),
            ],
        ),
        migrations.CreateModel(
            name='HonorOfKingsMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_1', models.FloatField(default=0)),
                ('star_2', models.FloatField(default=0)),
                ('star_3', models.FloatField(default=0)),
                ('star_4', models.FloatField(default=0)),
                ('star_5', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='honorOfKings.honorofkingsrank')),
            ],
        ),
        migrations.CreateModel(
            name='HonorOfKingsDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hok_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True)),
                ('current_marks', models.IntegerField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5')], null=True)),
                ('reached_marks', models.IntegerField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='honorOfKings.honorofkingsrank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='honorOfKings.honorofkingsrank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='honorOfKings.honorofkingsrank')),
            ],
        ),
    ]
