# Generated by Django 4.2.7 on 2024-02-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorOfKings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honorofkingsmark',
            name='star_4',
        ),
        migrations.RemoveField(
            model_name='honorofkingsmark',
            name='star_5',
        ),
        migrations.AlterField(
            model_name='honorofkingsdivisionorder',
            name='current_marks',
            field=models.IntegerField(blank=True, choices=[(0, '0 Stars'), (1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars')], null=True),
        ),
        migrations.AlterField(
            model_name='honorofkingsdivisionorder',
            name='reached_marks',
            field=models.IntegerField(blank=True, choices=[(0, '0 Stars'), (1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars')], null=True),
        ),
    ]
