# Generated by Django 4.2.7 on 2024-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorOfKings', '0002_remove_honorofkingsmark_star_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorofkingsdivisionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
