# Generated by Django 4.2.7 on 2024-01-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_baseorder_customer_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearthstoneRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='hearthstone/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_X_to_IX', models.FloatField(default=0)),
                ('from_IX_to_VIII', models.FloatField(default=0)),
                ('from_VIII_to_VII', models.FloatField(default=0)),
                ('from_VII_to_VI', models.FloatField(default=0)),
                ('from_VI_to_V', models.FloatField(default=0)),
                ('from_V_to_IV', models.FloatField(default=0)),
                ('from_IV_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_IV_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='hearthstone.hearthstonerank')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_3', models.FloatField(default=0)),
                ('marks_2', models.FloatField(default=0)),
                ('marks_1', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='hearthstone.hearthstonerank')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hearthstone_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'X'), (2, 'IX'), (3, 'VIII'), (4, 'VII'), (5, 'VI'), (6, 'V'), (7, 'IV'), (8, 'III'), (9, 'II'), (10, 'I')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'X'), (2, 'IX'), (3, 'VIII'), (4, 'VII'), (5, 'VI'), (6, 'V'), (7, 'IV'), (8, 'III'), (9, 'II'), (10, 'I')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'X'), (2, 'IX'), (3, 'VIII'), (4, 'VII'), (5, 'VI'), (6, 'V'), (7, 'IV'), (8, 'III'), (9, 'II'), (10, 'I')], null=True)),
                ('current_marks', models.IntegerField(blank=True, choices=[(0, '3'), (1, '2'), (2, '1')], null=True)),
                ('reached_marks', models.IntegerField(blank=True, choices=[(0, '3'), (1, '2'), (2, '1')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speed_up_boost', models.BooleanField(blank=True, default=True, null=True)),
                ('choose_legends', models.BooleanField(blank=True, default=True, null=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='hearthstone.hearthstonerank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='hearthstone.hearthstonerank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='hearthstone.hearthstonerank')),
            ],
        ),
    ]
