# Generated by Django 4.2.7 on 2024-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0002_rename_choose_legends_hearthstonedivisionorder_select_champion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearthstonedivisionorder',
            name='select_champion',
        ),
        migrations.AlterField(
            model_name='hearthstonedivisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Stars'), (1, '3 Stars'), (2, '2 Stars'), (3, '1 Stars')], null=True),
        ),
        migrations.AlterField(
            model_name='hearthstonedivisionorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Stars'), (1, '3 Stars'), (2, '2 Stars'), (3, '1 Stars')], null=True),
        ),
    ]
