# Generated by Django 4.2.7 on 2024-04-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0003_remove_hearthstonedivisionorder_select_champion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearthstonedivisionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
