# Generated by Django 5.0.4 on 2024-06-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_baseorder_payer_id_alter_promocode_code_and_more'),
        ('hearthstone', '0004_hearthstonedivisionorder_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearthstoneBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='hearthstone/images/')),
            ],
        ),
        migrations.CreateModel(
            name='HearthstoneBattlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_0_to_2000', models.FloatField(default=0)),
                ('from_2000_to_4000', models.FloatField(default=0)),
                ('from_4000_to_6000', models.FloatField(default=0)),
                ('from_6000_to_8000', models.FloatField(default=0)),
                ('from_8000_to_10000', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HearthStoneBattleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='hearthstone.hearthstonebattle')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='hearthstone.hearthstonebattle')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.baseorder')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='hearthstone.hearthstonebattle')),
            ],
        ),
    ]
