# Generated by Django 4.2.7 on 2024-01-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_baseorder_customer_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueOfLegendsPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='lol/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueOfLegendsRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='lol/images/')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueOfLegendsTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_IV_to_III', models.FloatField(default=0)),
                ('from_III_to_II', models.FloatField(default=0)),
                ('from_II_to_I', models.FloatField(default=0)),
                ('from_I_to_IV_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='leagueOfLegends.leagueoflegendsrank')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueOfLegendsPlacementOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lol_placement_order', serialize=False, to='accounts.baseorder')),
                ('number_of_match', models.IntegerField(default=5)),
                ('choose_champions', models.BooleanField(blank=True, default=False, null=True)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last_rank', to='leagueOfLegends.leagueoflegendsplacement')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueOfLegendsMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_0_20', models.FloatField(default=0)),
                ('marks_21_40', models.FloatField(default=0)),
                ('marks_41_60', models.FloatField(default=0)),
                ('marks_61_80', models.FloatField(default=0)),
                ('marks_81_99', models.FloatField(default=0)),
                ('marks_series', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='leagueOfLegends.leagueoflegendsrank')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueOfLegendsDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lol_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True)),
                ('current_marks', models.IntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-99'), (5, 'series')], null=True)),
                ('reached_marks', models.IntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-99'), (5, 'series')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choose_champions', models.BooleanField(blank=True, default=True, null=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='leagueOfLegends.leagueoflegendsrank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='leagueOfLegends.leagueoflegendsrank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='leagueOfLegends.leagueoflegendsrank')),
            ],
        ),
    ]
