# Generated by Django 4.2.7 on 2024-01-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueOfLegends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueoflegendsplacement',
            name='rank_image',
            field=models.ImageField(blank=True, null=True, upload_to='lol/images/'),
        ),
        migrations.AlterField(
            model_name='leagueoflegendsrank',
            name='rank_image',
            field=models.ImageField(blank=True, null=True, upload_to='lol/images/'),
        ),
    ]
