# Generated by Django 4.2.7 on 2024-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueOfLegends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagueoflegendsdivisionorder',
            old_name='choose_champions',
            new_name='select_champion',
        ),
        migrations.AlterField(
            model_name='leagueoflegendsdivisionorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='leagueoflegendsdivisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-99'), (5, 'series')], null=True),
        ),
        migrations.AlterField(
            model_name='leagueoflegendsdivisionorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='leagueoflegendsdivisionorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IV'), (2, 'III'), (3, 'II'), (4, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='leagueoflegendsdivisionorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-99'), (5, 'series')], null=True),
        ),
    ]
