# Generated by Django 4.2.7 on 2024-03-17 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leagueOfLegends', '0002_rename_choose_champions_leagueoflegendsdivisionorder_select_champion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagueoflegendsplacementorder',
            old_name='choose_champions',
            new_name='select_champion',
        ),
        migrations.AddField(
            model_name='leagueoflegendsplacementorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
