# Generated by Django 4.2.7 on 2024-01-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorantPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='valorant/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ValorantRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='valorant/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ValorantTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_I_to_II', models.FloatField(default=0)),
                ('from_II_to_III', models.FloatField(default=0)),
                ('from_III_to_I_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='valorant.valorantrank')),
            ],
        ),
        migrations.CreateModel(
            name='ValorantPlacementOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='valorant_placement_order', serialize=False, to='accounts.baseorder')),
                ('number_of_match', models.IntegerField(default=5)),
                ('choose_agents', models.BooleanField(blank=True, default=False, null=True)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last_rank', to='valorant.valorantplacement')),
            ],
        ),
        migrations.CreateModel(
            name='ValorantMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_0_20', models.FloatField(default=0)),
                ('marks_21_40', models.FloatField(default=0)),
                ('marks_41_60', models.FloatField(default=0)),
                ('marks_61_80', models.FloatField(default=0)),
                ('marks_81_100', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='valorant.valorantrank')),
            ],
        ),
        migrations.CreateModel(
            name='ValorantDivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='valorant_division_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('reached_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('desired_division', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], null=True)),
                ('current_marks', models.IntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-100')], null=True)),
                ('reached_marks', models.IntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-100')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choose_agents', models.BooleanField(blank=True, default=True, null=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='valorant.valorantrank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='valorant.valorantrank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='valorant.valorantrank')),
            ],
        ),
    ]
