# Generated by Django 4.2.7 on 2024-03-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorantdivisionorder',
            old_name='choose_agents',
            new_name='select_champion',
        ),
        migrations.RenameField(
            model_name='valorantplacementorder',
            old_name='choose_agents',
            new_name='select_champion',
        ),
    ]
