# Generated by Django 4.2.7 on 2024-03-17 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0002_rename_choose_agents_valorantdivisionorder_select_champion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorantplacementorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
