# Generated by Django 4.2.7 on 2024-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_champion_delete_championc'),
        ('valorant', '0003_valorantplacementorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorantdivisionorder',
            name='champions',
            field=models.ManyToManyField(blank=True, related_name='valo_division_champions', to='customer.champion'),
        ),
        migrations.AddField(
            model_name='valorantplacementorder',
            name='champions',
            field=models.ManyToManyField(blank=True, related_name='valo_placement_champions', to='customer.champion'),
        ),
        migrations.AlterField(
            model_name='valorantplacementorder',
            name='select_champion',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
