# Generated by Django 4.2.7 on 2024-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubgdivisionorder',
            old_name='choose_agents',
            new_name='select_champion',
        ),
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], null=True),
        ),
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-100')], null=True),
        ),
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], null=True),
        ),
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], null=True),
        ),
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0-20'), (1, '21-40'), (2, '41-60'), (3, '61-80'), (4, '81-100')], null=True),
        ),
    ]
