# Generated by Django 4.2.7 on 2024-03-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0002_rename_choose_agents_pubgdivisionorder_select_champion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubgmark',
            name='marks_0_20',
        ),
        migrations.RemoveField(
            model_name='pubgmark',
            name='marks_21_40',
        ),
        migrations.RemoveField(
            model_name='pubgmark',
            name='marks_41_60',
        ),
        migrations.RemoveField(
            model_name='pubgmark',
            name='marks_61_80',
        ),
        migrations.RemoveField(
            model_name='pubgmark',
            name='marks_81_100',
        ),
        migrations.RemoveField(
            model_name='pubgmark',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='pubgrank',
            name='rank_image',
        ),
        migrations.RemoveField(
            model_name='pubgrank',
            name='rank_name',
        ),
        migrations.RemoveField(
            model_name='pubgtier',
            name='from_III_to_II',
        ),
        migrations.RemoveField(
            model_name='pubgtier',
            name='from_II_to_I',
        ),
        migrations.RemoveField(
            model_name='pubgtier',
            name='from_VI_to_III',
        ),
        migrations.RemoveField(
            model_name='pubgtier',
            name='from_V_to_VI',
        ),
        migrations.RemoveField(
            model_name='pubgtier',
            name='rank',
        ),
    ]
