# Generated by Django 4.2.7 on 2024-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0004_pubgmark_marks_0_20_pubgmark_marks_21_40_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='pubgdivisionorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True),
        ),
    ]
