# Generated by Django 4.2.7 on 2024-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0005_alter_pubgdivisionorder_current_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubgdivisionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
