# Generated by Django 4.2.7 on 2024-01-06 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valorant', '__first__'),
        ('wildRift', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=500, null=True)),
                ('game', models.IntegerField(default=1)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_rated', to='accounts.baseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/booster/')),
                ('about_you', models.TextField(blank=True, max_length=1000, null=True)),
                ('can_choose_me', models.BooleanField(blank=True, default=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_wf_player', models.BooleanField(default=False)),
                ('is_valo_player', models.BooleanField(default=False)),
                ('achived_rank_valo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valo_rank', to='valorant.valorantrank')),
                ('achived_rank_wr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wr_rank', to='wildRift.wildriftrank')),
                ('booster', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
