# Generated by Django 4.2.7 on 2024-01-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '__first__'),
        ('booster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_pubg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubg_rank', to='pubg.pubgrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_pubg_player',
            field=models.BooleanField(default=False),
        ),
    ]
