# Generated by Django 4.2.7 on 2024-01-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagueOfLegends', '__first__'),
        ('booster', '0002_booster_achived_rank_pubg_booster_is_pubg_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_lol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lol_rank', to='leagueOfLegends.leagueoflegendsrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_lol_player',
            field=models.BooleanField(default=False),
        ),
    ]
