# Generated by Django 4.2.7 on 2024-01-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '__first__'),
        ('booster', '0003_booster_achived_rank_lol_booster_is_lol_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_tft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearthstone_rank', to='hearthstone.hearthstonerank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_hearthstone_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_tft_player',
            field=models.BooleanField(default=False),
        ),
    ]
