# Generated by Django 4.2.7 on 2024-02-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocketLeague', '__first__'),
        ('tft', '0001_initial'),
        ('hearthstone', '0001_initial'),
        ('booster', '0004_booster_achived_rank_tft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_hearthstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearthstone_rank', to='hearthstone.hearthstonerank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='achived_rank_rl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rl_rank', to='rocketLeague.rocketleaguerank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_rl_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_tft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tft_rank', to='tft.tftrank'),
        ),
    ]
