# Generated by Django 4.2.7 on 2024-02-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0003_alter_mobilelegendsdivisionorder_current_division_and_more'),
        ('booster', '0005_booster_achived_rank_hearthstone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_modleg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobleg_rank', to='mobileLegends.mobilelegendsrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_mobleg_player',
            field=models.BooleanField(default=False),
        ),
    ]
