# Generated by Django 4.2.7 on 2024-02-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '__first__'),
        ('booster', '0006_booster_achived_rank_modleg_booster_is_mobleg_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_wow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wow_rank', to='WorldOfWarcraft.wowrank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_wow_player',
            field=models.BooleanField(default=False),
        ),
    ]
