# Generated by Django 4.2.7 on 2024-02-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch2', '0001_initial'),
        ('booster', '0007_booster_achived_rank_wow_booster_is_wow_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_overwatch2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overwatch2_rank', to='overwatch2.overwatch2rank'),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_overwatch2_player',
            field=models.BooleanField(default=False),
        ),
    ]
