# Generated by Django 4.2.7 on 2024-02-25 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_promocode_description'),
        ('booster', '0008_booster_achived_rank_overwatch2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=500, null=True)),
                ('game', models.IntegerField(default=1)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booster', models.ForeignKey(limit_choices_to={'is_booster': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_rated', to='accounts.baseorder')),
            ],
        ),
        migrations.AlterField(
            model_name='booster',
            name='booster',
            field=models.OneToOneField(limit_choices_to={'is_booster': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
