# Generated by Django 4.2.7 on 2024-02-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0009_orderrating_alter_booster_booster_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='is_csgo2_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_dota2_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booster',
            name='is_hok_player',
            field=models.BooleanField(default=False),
        ),
    ]
