# Generated by Django 4.0 on 2024-03-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0002_worldofwarcraftarenaboostorder_worldofwarcraftrank_and_more'),
        ('booster', '0010_booster_is_csgo2_player_booster_is_dota2_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_wow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wow_rank', to='WorldOfWarcraft.worldofwarcraftrank'),
        ),
    ]
