# Generated by Django 4.2.7 on 2024-03-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0007_dota2rankboostorder_mmr_price'),
        ('booster', '0011_alter_booster_achived_rank_wow'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_dota2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dota2_rank', to='dota2.dota2rank'),
        ),
    ]
