# Generated by Django 4.2.7 on 2024-03-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo2', '0006_csgo2premierprice_csgo2premierrank_csgofaceitprice_and_more'),
        ('booster', '0012_booster_achived_rank_dota2'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_csgo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csgo2_rank', to='csgo2.csgo2rank'),
        ),
    ]
