# Generated by Django 4.2.7 on 2024-03-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honorOfKings', '0002_remove_honorofkingsmark_star_4_and_more'),
        ('booster', '0013_booster_achived_rank_csgo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='achived_rank_hok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hok_rank', to='honorOfKings.honorofkingsrank'),
        ),
    ]
