# Generated by Django 4.2.7 on 2024-03-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0014_booster_achived_rank_hok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booster',
            old_name='achived_rank_modleg',
            new_name='achived_rank_mobleg',
        ),
    ]
