# Generated by Django 4.2.7 on 2024-04-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('booster', '0015_rename_achived_rank_modleg_booster_achived_rank_mobleg'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('discord_id', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('game', models.ManyToManyField(to='games.game')),
            ],
        ),
    ]
