# Generated by Django 4.2.7 on 2024-04-04 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0016_workwithus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booster.workwithus')),
            ],
        ),
    ]
