# Generated by Django 4.2.7 on 2024-04-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0017_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booster',
            old_name='is_wf_player',
            new_name='is_wr_player',
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
