# Generated by Django 4.2.7 on 2024-04-08 15:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('booster', '0018_rename_is_wf_player_booster_is_wr_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booster',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='booster',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booster',
            name='games',
            field=models.ManyToManyField(related_name='games', to='games.game'),
        ),
        migrations.AddField(
            model_name='booster',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='booster/images'),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='languages',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='rank',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='BoosterPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booster/images')),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_portfolio', to='booster.booster')),
            ],
        ),
    ]
