# Generated by Django 4.2.7 on 2024-04-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorldOfWarcraft', '0007_worldofwarcraftrank1_and_more'),
        ('booster', '0019_rename_image_booster_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_wow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wow_rank', to='WorldOfWarcraft.worldofwarcraftrank1'),
        ),
    ]
