# Generated by Django 4.2.7 on 2024-04-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0023_alter_booster_achived_rank_wow'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='paypal_account',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
