# Generated by Django 4.2.7 on 2024-04-15 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildRift', '0009_wildriftrank_and_more'),
        ('booster', '0025_alter_booster_achived_rank_wr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_wr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wr_rank', to='wildRift.wildriftrank'),
        ),
    ]
