# Generated by Django 4.2.7 on 2024-04-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocketLeague', '0007_rocketleagueplacement_rocketleaguerank_and_more'),
        ('booster', '0036_alter_booster_achived_rank_rl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_rl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rl_rank', to='rocketLeague.rocketleaguerank'),
        ),
    ]
