# Generated by Django 5.0.4 on 2024-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0037_alter_booster_achived_rank_rl'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
