# Generated by Django 5.0.4 on 2024-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0038_booster_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='boosters%2F'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='profile_image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
