# Generated by Django 5.0.4 on 2024-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0039_alter_booster_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
