# Generated by Django 5.0.4 on 2024-04-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0040_alter_booster_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='choosen_chat_message',
            field=models.CharField(default='Hello'),
        ),
        migrations.AddField(
            model_name='booster',
            name='start_chat_message',
            field=models.CharField(default='Hello'),
        ),
    ]
