# Generated by Django 5.0.4 on 2024-04-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0041_booster_choosen_chat_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='choosen_chat_message',
            field=models.CharField(default='Thank you for choose me as your booster, '),
        ),
        migrations.AlterField(
            model_name='booster',
            name='start_chat_message',
            field=models.CharField(default='Hello I will be your booster'),
        ),
    ]
