# Generated by Django 5.0.4 on 2024-04-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0042_alter_booster_choosen_chat_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
            ],
        ),
    ]
