# Generated by Django 5.0.4 on 2024-04-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0043_createbooster'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbooster',
            name='is_csgo2_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_dota2_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_hearthstone_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_hok_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_lol_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_mobleg_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_overwatch2_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_pubg_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_rl_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_tft_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_valo_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_wow_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createbooster',
            name='is_wr_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booster',
            name='can_choose_me',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
