# Generated by Django 5.0.4 on 2024-04-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0046_workwithus_about_you_workwithus_agree_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workwithus',
            name='agree_privacy',
            field=models.BooleanField(),
        ),
    ]
