# Generated by Django 5.0.4 on 2024-04-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0047_alter_workwithus_agree_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='languages',
        ),
        migrations.AddField(
            model_name='workwithus',
            name='languages',
            field=models.ManyToManyField(to='booster.language'),
        ),
    ]
