# Generated by Django 5.0.4 on 2024-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0048_language_remove_workwithus_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
