# Generated by Django 5.0.4 on 2024-04-28 02:17

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0049_alter_language_language'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWithUss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('discord_id', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=300)),
                ('server', models.CharField(max_length=100)),
                ('about_you', models.TextField(max_length=1000)),
                ('country', django_countries.fields.CountryField(max_length=1000)),
                ('agree_privacy', models.BooleanField()),
                ('game', models.ManyToManyField(to='games.game')),
                ('languages', models.ManyToManyField(to='booster.language')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='booster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booster.workwithuss'),
        ),
        migrations.DeleteModel(
            name='WorkWithUs',
        ),
    ]
