# Generated by Django 5.0.4 on 2024-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0051_workwithus_alter_photo_booster_delete_workwithuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booster',
            name='languages',
        ),
        migrations.AddField(
            model_name='booster',
            name='languages',
            field=models.ManyToManyField(to='booster.language'),
        ),
    ]
