# Generated by Django 5.0.4 on 2024-05-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0052_remove_booster_languages_booster_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='choosen_chat_message',
            field=models.CharField(default='Thank you for choose me as your booster, ', max_length=200),
        ),
        migrations.AlterField(
            model_name='booster',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booster',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booster',
            name='start_chat_message',
            field=models.CharField(default='Hello I will be your booster', max_length=200),
        ),
    ]
