# Generated by Django 5.0.4 on 2024-05-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0056_alter_booster_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booster',
            name='profile_image_url',
        ),
    ]
