# Generated by Django 5.0.4 on 2024-05-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0057_remove_booster_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='booster/'),
        ),
    ]
