# Generated by Django 5.0.4 on 2024-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0058_alter_booster_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='booster/images/'),
        ),
    ]
