# Generated by Django 5.0.4 on 2024-05-11 17:30

import booster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0059_alter_booster_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=booster.models.profile_image_upload_path),
        ),
    ]
