# Generated by Django 5.0.4 on 2024-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0060_alter_booster_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosterportfolio',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
