# Generated by Django 5.0.4 on 2024-05-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0061_boosterportfolio_approved'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='rank/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game')),
            ],
        ),
    ]
