# Generated by Django 5.0.4 on 2024-05-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0062_boosterrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_csgo2',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 13}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csgo2_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_dota2',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dota2_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_hearthstone',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearthstone_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_hok',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 11}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hok_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_lol',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lol_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_mobleg',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobleg_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_overwatch2',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 12}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overwatch2_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_pubg',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubg_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_rl',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 9}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rl_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_tft',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tft_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_valo',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valo_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_wow',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wow_rank', to='booster.boosterrank'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='achived_rank_wr',
            field=models.ForeignKey(blank=True, limit_choices_to={'game__pk': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wr_rank', to='booster.boosterrank'),
        ),
    ]
