# Generated by Django 5.0.4 on 2024-05-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0063_alter_booster_achived_rank_csgo2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boosterrank',
            old_name='rank',
            new_name='rank_name',
        ),
    ]
