# Generated by Django 5.0.4 on 2024-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0064_rename_rank_boosterrank_rank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosterrank',
            name='base',
            field=models.ImageField(blank=True, null=True, upload_to='rank/'),
        ),
    ]
