# Generated by Django 5.0.4 on 2024-05-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0065_boosterrank_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosterrank',
            name='base',
        ),
    ]
