# Generated by Django 5.0.4 on 2024-06-10 01:58

import booster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0066_remove_boosterrank_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booster',
            name='choosen_chat_message',
        ),
        migrations.RemoveField(
            model_name='booster',
            name='start_chat_message',
        ),
        migrations.AlterField(
            model_name='booster',
            name='about_you',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booster',
            name='profile_image',
            field=models.ImageField(blank=True, default='/booster/images/27/ed5a10fa-3efe-41ed-a5f6-dc518d3393ef.webp', null=True, upload_to=booster.models.profile_image_upload_path),
        ),
    ]
