# Generated by Django 4.2.7 on 2024-03-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='games/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='games/banners/')),
                ('name_image', models.ImageField(blank=True, null=True, upload_to='games/names/')),
            ],
        ),
    ]
