# Generated by Django 4.2.7 on 2024-03-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0035_alter_tokenforpay_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csgo2Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='csgo2/images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=25)),
                ('rank_image', models.ImageField(blank=True, null=True, upload_to='csgo2/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_I_to_I_next', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='csgo2.csgo2rank')),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2PlacementOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_placement_order', serialize=False, to='accounts.baseorder')),
                ('number_of_match', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_rank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ovw2_last_rank', to='csgo2.csgo2placement')),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_number', models.PositiveSmallIntegerField(default=5)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='csgo2.csgo2rank')),
            ],
        ),
        migrations.CreateModel(
            name='Csgo2DivisionOrder',
            fields=[
                ('order', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_order', serialize=False, to='accounts.baseorder')),
                ('current_division', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('reached_division', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('desired_division', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('current_marks', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('reached_marks', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='current_rank', to='csgo2.csgo2rank')),
                ('desired_rank', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='desired_rank', to='csgo2.csgo2rank')),
                ('reached_rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reached_rank', to='csgo2.csgo2rank')),
            ],
        ),
    ]
