# Generated by Django 4.2.7 on 2024-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csgo2placementorder',
            name='last_rank',
        ),
        migrations.RemoveField(
            model_name='csgo2placementorder',
            name='order',
        ),
        migrations.AlterField(
            model_name='csgo2divisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Csgo2Placement',
        ),
        migrations.DeleteModel(
            name='Csgo2PlacementOrder',
        ),
    ]
