# Generated by Django 4.2.7 on 2024-03-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo2', '0002_remove_csgo2placementorder_last_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csgo2mark',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='csgo2tier',
            name='rank',
        ),
        migrations.DeleteModel(
            name='Csgo2DivisionOrder',
        ),
        migrations.DeleteModel(
            name='Csgo2Mark',
        ),
        migrations.DeleteModel(
            name='Csgo2Rank',
        ),
        migrations.DeleteModel(
            name='Csgo2Tier',
        ),
    ]
