# Generated by Django 4.2.7 on 2024-03-20 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_baseorder_game_type'),
        ('csgo2', '0005_csgo2premierorder_csgofaceitorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csgo2PremierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_0_4999', models.FloatField(default=5.42)),
                ('price_5000_7999', models.FloatField(default=6.77)),
                ('price_8000_11999', models.FloatField(default=11.28)),
                ('price_12000_18999', models.FloatField(default=16.28)),
                ('price_19000_20999', models.FloatField(default=30.35)),
                ('price_21000_24999', models.FloatField(default=37.61)),
                ('price_25000_30000', models.FloatField(default=60.17)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Csgo2PremierRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=300)),
                ('start_range', models.IntegerField()),
                ('end_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CsgoFaceitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_1_to_2', models.FloatField(default=16.68)),
                ('from_2_to_3', models.FloatField(default=16.68)),
                ('from_3_to_4', models.FloatField(default=19.43)),
                ('from_4_to_5', models.FloatField(default=20.83)),
                ('from_5_to_6', models.FloatField(default=23.6)),
                ('from_6_to_7', models.FloatField(default=27.77)),
                ('from_7_to_8', models.FloatField(default=34.72)),
                ('from_8_to_9', models.FloatField(default=48.6)),
                ('from_9_to_10', models.FloatField(default=62.48)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='csgo2premierorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='csgofaceitorder',
            name='id',
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_premier_order', serialize=False, to='accounts.baseorder'),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='csgofaceitorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csgofaceitorder',
            name='current_level',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='csgofaceitorder',
            name='desired_level',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='csgofaceitorder',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_faceit_order', serialize=False, to='accounts.baseorder'),
        ),
        migrations.AddField(
            model_name='csgofaceitorder',
            name='reached_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='csgofaceitorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='csgo2divisionorder',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='csgo2_division_order', serialize=False, to='accounts.baseorder'),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='current_rank',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='current_rank', to='csgo2.csgo2premierrank'),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='desired_rank',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='desired_rank', to='csgo2.csgo2premierrank'),
        ),
        migrations.AddField(
            model_name='csgo2premierorder',
            name='reached_rank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reached_rank', to='csgo2.csgo2premierrank'),
        ),
    ]
