# Generated by Django 5.0.4 on 2024-04-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo2', '0006_csgo2premierprice_csgo2premierrank_csgofaceitprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csgo2rank',
            name='rank_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
