# Generated by Django 4.2.7 on 2024-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilelegendstier',
            name='from_V_to_IV',
            field=models.FloatField(default=0),
        ),
    ]
