# Generated by Django 4.2.7 on 2024-02-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0002_mobilelegendstier_from_v_to_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_division',
            field=models.IntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_marks',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='desired_division',
            field=models.IntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_division',
            field=models.IntegerField(blank=True, choices=[(1, 'V'), (2, 'IV'), (3, 'III'), (4, 'II'), (5, 'I')], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_marks',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True),
        ),
    ]
