# Generated by Django 4.2.7 on 2024-03-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0003_alter_mobilelegendsdivisionorder_current_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilelegendstier',
            old_name='from_I_to_IV_next',
            new_name='from_I_to_V_next',
        ),
    ]
