# Generated by Django 4.2.7 on 2024-03-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0004_rename_from_i_to_iv_next_mobilelegendstier_from_i_to_v_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilelegendsmark',
            name='marks_series',
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_division',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='desired_division',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_division',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
    ]
