# Generated by Django 4.2.7 on 2024-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0005_remove_mobilelegendsmark_marks_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True),
        ),
    ]
