# Generated by Django 4.2.7 on 2024-03-02 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0006_alter_mobilelegendsdivisionorder_current_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilelegendsmark',
            old_name='marks_0_20',
            new_name='star_1',
        ),
        migrations.RenameField(
            model_name='mobilelegendsmark',
            old_name='marks_21_40',
            new_name='star_2',
        ),
        migrations.RenameField(
            model_name='mobilelegendsmark',
            old_name='marks_41_60',
            new_name='star_3',
        ),
        migrations.RenameField(
            model_name='mobilelegendsmark',
            old_name='marks_61_80',
            new_name='star_4',
        ),
        migrations.RenameField(
            model_name='mobilelegendsmark',
            old_name='marks_81_99',
            new_name='star_5',
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='desired_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_division',
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
