# Generated by Django 4.2.7 on 2024-03-02 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0007_rename_marks_0_20_mobilelegendsmark_star_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilelegendsdivisionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_rank',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'id__range': (1, 9)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='mobileLegends.mobilelegendsrank'),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='desired_rank',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'id__range': (1, 10)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='mobileLegends.mobilelegendsrank'),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_rank',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'id__range': (1, 10)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reached_rank', to='mobileLegends.mobilelegendsrank'),
        ),
    ]
