# Generated by Django 4.2.7 on 2024-03-02 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0008_mobilelegendsdivisionorder_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='current_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Star'), (1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mobilelegendsdivisionorder',
            name='reached_marks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 Star'), (1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
