# Generated by Django 4.2.7 on 2024-04-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0011_mobilelegendsmark2_delete_mobilelegendsmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileLegendsMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_1', models.FloatField(default=0)),
                ('star_2', models.FloatField(default=0)),
                ('star_3', models.FloatField(default=0)),
                ('star_4', models.FloatField(default=0)),
                ('star_5', models.FloatField(default=0)),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='mobileLegends.mobilelegendsrank')),
            ],
        ),
        migrations.DeleteModel(
            name='MobileLegendsMark2',
        ),
    ]
