# Generated by Django 4.2.7 on 2024-04-13 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLegends', '0012_mobilelegendsmark_delete_mobilelegendsmark2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilelegendsplacementorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilelegendsplacementorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
